# Generated by Django 2.0.2 on 2018-02-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_blogdata_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdata',
            name='link',
        ),
    ]
