# Generated by Django 2.0.2 on 2018-02-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_remove_blogdata_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
