# Generated by Django 2.0.2 on 2018-02-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0004_blogdata_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
