# Generated by Django 2.0.2 on 2018-02-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0007_auto_20180223_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='link',
            field=models.URLField(),
        ),
    ]
